import os
import json

HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MarketPulse 分析报告 - {keyword}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
    <style>
        :root {{
            --bg: #0f172a;
            --card: #1e293b;
            --text: #f8fafc;
            --ac: #38bdf8;
            --gr: #4ade80;
            --rd: #f87171;
            --b: #334155;
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
            background: var(--bg);
            color: var(--text);
            min-height: 100vh;
        }}
        .container {{ max-width: 1200px; margin: 0 auto; padding: 32px 24px; }}
        h1 {{ font-size: 28px; color: var(--ac); margin-bottom: 32px; }}
        h2 {{ font-size: 16px; color: #94a3b8; margin-bottom: 16px; text-transform: uppercase; letter-spacing: 0.8px; }}
        .metrics-grid {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 16px;
            margin-bottom: 24px;
        }}
        @media (max-width: 768px) {{ .metrics-grid {{ grid-template-columns: repeat(2, 1fr); }} }}
        .metric-card {{
            background: var(--card);
            border: 1px solid var(--b);
            border-radius: 12px;
            padding: 20px;
            text-align: center;
        }}
        .metric-label {{ font-size: 12px; color: #64748b; margin-bottom: 8px; }}
        .metric-value {{ font-size: 28px; font-weight: 700; font-family: 'JetBrains Mono', monospace; }}
        .metric-value.pos {{ color: var(--gr); }}
        .metric-value.neg {{ color: var(--rd); }}
        .metric-value.ac {{ color: var(--ac); }}
        .charts-grid {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 16px;
            margin-bottom: 24px;
        }}
        @media (max-width: 768px) {{ .charts-grid {{ grid-template-columns: 1fr; }} }}
        .card {{
            background: var(--card);
            border: 1px solid var(--b);
            border-radius: 12px;
            padding: 24px;
        }}
        .card canvas {{ max-height: 300px; }}
        .news-list {{ list-style: none; }}
        .news-item {{
            padding: 12px 16px;
            border-bottom: 1px solid var(--b);
            display: flex;
            gap: 12px;
            align-items: flex-start;
        }}
        .news-item:last-child {{ border-bottom: none; }}
        .news-badge {{
            font-size: 11px;
            font-weight: 600;
            padding: 2px 8px;
            border-radius: 4px;
            white-space: nowrap;
        }}
        .news-badge.pos {{ background: rgba(74,222,128,0.15); color: var(--gr); }}
        .news-badge.neg {{ background: rgba(248,113,113,0.15); color: var(--rd); }}
        .news-badge.neutral {{ background: rgba(148,163,184,0.15); color: #94a3b8; }}
        .news-link {{ color: #60a5fa; text-decoration: none; }}
        .news-link:hover {{ text-decoration: underline; }}
        .footer {{ text-align: center; margin-top: 32px; padding-top: 24px; border-top: 1px solid var(--b); color: #64748b; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>MarketPulse 分析报告 — {keyword}</h1>

        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-label">总新闻数</div>
                <div class="metric-value ac">{total_news}</div>
            </div>
            <div class="metric-card">
                <div class="metric-label">平均情绪分</div>
                <div class="metric-value {sentiment_class}">{avg_sentiment}</div>
            </div>
            <div class="metric-card">
                <div class="metric-label">积极 / 消极</div>
                <div class="metric-value"><span class="pos">{positive_count}</span> / <span class="neg">{negative_count}</span></div>
            </div>
            <div class="metric-card">
                <div class="metric-label">趋势预测</div>
                <div class="metric-value {trend_class}">{trend_direction}</div>
            </div>
        </div>

        <div class="charts-grid">
            <div class="card">
                <h2>情绪分布</h2>
                <canvas id="sentimentChart"></canvas>
            </div>
            <div class="card">
                <h2>趋势预测</h2>
                <canvas id="trendChart"></canvas>
            </div>
        </div>

        <div class="card">
            <h2>关键新闻节选</h2>
            <ul class="news-list" id="newsList"></ul>
        </div>

        <div class="footer">Generated by MarketPulse BettaFish — {gen_time}</div>
    </div>

    <script>
        var reportData = __REPORT_DATA_PLACEHOLDER__;

        (function() {{
            var dist = (reportData.sentiment_summary || {{}}).sentiment_distribution || {{}};
            var ctx1 = document.getElementById('sentimentChart').getContext('2d');
            new Chart(ctx1, {{
                type: 'doughnut',
                data: {{
                    labels: ['积极', '中性', '消极'],
                    datasets: [{{
                        data: [dist.positive || 0, dist.neutral || 0, dist.negative || 0],
                        backgroundColor: ['#4ade80', '#94a3b8', '#f87171'],
                        borderColor: '#1e293b',
                        borderWidth: 2
                    }}]
                }},
                options: {{
                    responsive: true,
                    cutout: '62%',
                    plugins: {{ legend: {{ position: 'bottom', labels: {{ color: '#94a3b8', padding: 16 }} }} }}
                }}
            }});

            var trendResults = reportData.trend_results || {{}};
            var predictions = trendResults.predictions || [];
            var ctx2 = document.getElementById('trendChart').getContext('2d');
            new Chart(ctx2, {{
                type: 'line',
                data: {{
                    labels: predictions.map(function(r) {{ return new Date(r.ds).toLocaleDateString('zh-CN'); }}),
                    datasets: [{{
                        label: '情绪预测',
                        data: predictions.map(function(r) {{ return r.yhat; }}),
                        borderColor: '#38bdf8',
                        backgroundColor: 'rgba(56,189,248,0.1)',
                        fill: true,
                        tension: 0.4,
                        pointRadius: 3,
                        pointBackgroundColor: '#38bdf8'
                    }}]
                }},
                options: {{
                    responsive: true,
                    scales: {{
                        x: {{ ticks: {{ color: '#64748b' }}, grid: {{ color: '#1e293b' }} }},
                        y: {{ ticks: {{ color: '#64748b' }}, grid: {{ color: '#1e293b' }} }}
                    }},
                    plugins: {{ legend: {{ labels: {{ color: '#94a3b8' }} }} }}
                }}
            }});

            var newsList = document.getElementById('newsList');
            (reportData.analyzed_news || []).slice(0, 8).forEach(function(n) {{
                var li = document.createElement('li');
                li.className = 'news-item';
                var label = n.sentiment_label || 'neutral';
                var labelText = label === 'positive' ? '+正面' : label === 'negative' ? '-负面' : '○中性';
                li.innerHTML = '<span class="news-badge ' + label + '">' + labelText + '</span>'
                    + '<a class="news-link" href="' + (n.url || '#') + '" target="_blank">' + (n.title || '') + '</a>';
                newsList.appendChild(li);
            }});
        }})();
    </script>
</body>
</html>
"""


def export_html_report(report_data: dict, output_path: str) -> str:
    """生成交互式 HTML 分析报告"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    keyword = report_data.get("keyword", "未知")
    sentiment_summary = report_data.get("sentiment_summary", {})
    trend_summary = report_data.get("trend_summary", {})

    avg_sentiment = sentiment_summary.get("avg_sentiment", 0.0)
    sentiment_class = "pos" if avg_sentiment > 0.1 else ("neg" if avg_sentiment < -0.1 else "ac")

    trend_direction = trend_summary.get("trend_direction", "未知")
    trend_direction_map = {"positive": "看涨", "negative": "看跌", "neutral": "平稳"}
    trend_display = trend_direction_map.get(trend_direction, trend_direction)
    trend_class = "pos" if trend_direction == "positive" else ("neg" if trend_direction == "negative" else "ac")

    from datetime import datetime
    gen_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    html_content = HTML_TEMPLATE.format(
        keyword=keyword,
        total_news=sentiment_summary.get("total_news", 0),
        avg_sentiment=f"{avg_sentiment:+.3f}",
        sentiment_class=sentiment_class,
        positive_count=sentiment_summary.get("positive_count", 0),
        negative_count=sentiment_summary.get("negative_count", 0),
        trend_direction=trend_display,
        trend_class=trend_class,
        gen_time=gen_time,
    )

    # 安全注入 JSON 数据 —— 使用 replace 避免 format() 对花括号的二次解析
    report_json = json.dumps(report_data, ensure_ascii=False, default=str)
    html_content = html_content.replace("__REPORT_DATA_PLACEHOLDER__", report_json)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    return output_path
